[build]
  functions = "build/functions/"
  command = "npm run build"

[build.environment]
  HN_DATABASE_URL = "https://hacker-news.firebaseio.com/v0"

[[redirects]]
  from = "/api/stories/:id/comments"
  to = "/.netlify/functions/getStoryComments/:id"
  status = 200

[[redirects]]
  from = "/api/stories/:id"
  to = "/.netlify/functions/getStory/:id"
  status = 200

[[redirects]]
  from = "/api/feeds/:name"
  to = "/.netlify/functions/getFeeds/:name"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200